services:
  remnawave-tg-bot:
    build: 
      context: .
      network: host
      args:
        USER_NAME: ${USER_NAME:-appuser}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: remnawave-tg-bot
    hostname: remnawave-tg-bot
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      # named volume for db and host bind mount for logs
      - bot-db:/app/data/db
      - ./data/logs:/app/data/logs  
    # network_mode: host
    networks:
      - remnawave-network
    restart: unless-stopped

networks:
  remnawave-network:
    external: true

volumes:
  bot-db:
    driver: local
