services:
  krisa-bot:
    build:
      context: .
      network: host
      args:
        USER_NAME: ${USER_NAME:-appuser}
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: krisa-bot:dev
    container_name: krisa-bot
    hostname: krisa-bot
    ports:
      - "4000:4000"
    env_file:
      - .env
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    volumes:
      # named volume for db and host bind mount for logs
      - bot-db:/app/data/db
      - ./data/logs:/app/data/logs
    networks:
      - remnawave-network

networks:
  remnawave-network:
    external: true

volumes:
  bot-db:
    driver: local
