services:
  remnawave-tg-bot:
    build: 
      context: .
      network: host
    container_name: remnawave-tg-bot
    hostname: remnawave-tg-bot
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./db/bot.db:/app/db/bot.db  # Persist SQLite database on host
      - ./logs:/app/logs
    # network_mode: host
    networks:
      - remnawave-network
    restart: unless-stopped

networks:
  remnawave-network:
    external: true

